-- MySQL Script generated by MySQL Workbench
-- Wed Mar 10 20:18:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreUsuario`, `contraseña`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Usuario_nombreUsuario` VARCHAR(45) NOT NULL,
  `Usuario_contraseña` VARCHAR(45) NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `IdDocumento` INT(10) NOT NULL,
  `tipoDocumento` VARCHAR(2) NOT NULL,
  `correoElectronico` VARCHAR(45) NOT NULL COMMENT 'Create email constraint',
  `Celular` INT(10) NOT NULL,
  PRIMARY KEY (`IdCliente`, `Usuario_nombreUsuario`, `Usuario_contraseña`),
  UNIQUE INDEX `IdCliente_UNIQUE` (`IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Usuario`
    FOREIGN KEY (`Usuario_nombreUsuario` , `Usuario_contraseña`)
    REFERENCES `mydb`.`Usuario` (`nombreUsuario` , `contraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PuntoDeVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PuntoDeVenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PuntoDeVenta` (
  `idPuntodeVenta` INT NOT NULL,
  `Usuario_nombreUsuario` VARCHAR(45) NOT NULL,
  `Usuario_contraseña` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipoPuntoVenta` INT(1) NOT NULL,
  `urlUbicacion` VARCHAR(45) NOT NULL,
  `PuntoDeVentacol` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idPuntodeVenta`, `Usuario_nombreUsuario`, `Usuario_contraseña`),
  INDEX `fk_PuntoDeVenta_Usuario1_idx` (`Usuario_nombreUsuario` ASC, `Usuario_contraseña` ASC) VISIBLE,
  CONSTRAINT `fk_PuntoDeVenta_Usuario1`
    FOREIGN KEY (`Usuario_nombreUsuario` , `Usuario_contraseña`)
    REFERENCES `mydb`.`Usuario` (`nombreUsuario` , `contraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MétodoDePago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MétodoDePago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MétodoDePago` (
  `Cliente_IdCliente` INT NOT NULL,
  `idMetodo` INT NOT NULL,
  PRIMARY KEY (`Cliente_IdCliente`, `idMetodo`),
  CONSTRAINT `fk_MétodoDePago_Cliente1`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nequi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nequi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nequi` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCelular` INT(10) NOT NULL,
  PRIMARY KEY (`numeroCelular`),
  INDEX `fk_Nequi_MétodoDePago1_idx` (`MétodoDePago_Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Nequi_MétodoDePago1`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `mydb`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PSE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PSE` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCuenta` INT(11) NOT NULL,
  PRIMARY KEY (`numeroCuenta`),
  INDEX `fk_PSE_MétodoDePago1_idx` (`MétodoDePago_Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_PSE_MétodoDePago1`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `mydb`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Daviplata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Daviplata` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Daviplata` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCelular` INT(10) NOT NULL,
  PRIMARY KEY (`numeroCelular`),
  INDEX `fk_Daviplata_MétodoDePago1_idx` (`MétodoDePago_Cliente_IdCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Daviplata_MétodoDePago1`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `mydb`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
