-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 15:47:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `nombreUsuario` VARCHAR(20) NOT NULL,
  `contraseña` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`nombreUsuario`, `contraseña`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Usuario_nombreUsuario` VARCHAR(20) NOT NULL,
  `Usuario_contraseña` VARCHAR(16) NOT NULL,
  `nombreCompleto` VARCHAR(30) NOT NULL,
  `tipoDocumento` VARCHAR(2) NOT NULL,
  `idDocumento` BIGINT(11) NOT NULL,
  `correoElectronico` VARCHAR(40) NOT NULL COMMENT 'Create email constraint',
  `celular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`IdCliente`, `Usuario_nombreUsuario`, `Usuario_contraseña`),
  UNIQUE INDEX `IdCliente_UNIQUE` (`IdCliente` ASC),
  INDEX `fk_Cliente_Usuario_idx` (`Usuario_nombreUsuario` ASC, `Usuario_contraseña` ASC),
  UNIQUE INDEX `Usuario_nombreUsuario_UNIQUE` (`Usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_Cliente_Usuario`
    FOREIGN KEY (`Usuario_nombreUsuario` , `Usuario_contraseña`)
    REFERENCES `mydb`.`Usuario` (`nombreUsuario` , `contraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MétodoDePago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MétodoDePago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MétodoDePago` (
  `Cliente_IdCliente` INT NOT NULL,
  `idMetodo` INT NOT NULL,
  PRIMARY KEY (`Cliente_IdCliente`, `idMetodo`),
  INDEX `fk_MétodoDePago_Cliente` (`Cliente_IdCliente` ASC),
  CONSTRAINT `fk_MétodoDePago_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nequi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nequi` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Nequi` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCelular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`numeroCelular`),
  INDEX `fk_Nequi_MétodoDePago_idx` (`MétodoDePago_Cliente_IdCliente` ASC),
  CONSTRAINT `fk_Nequi_MétodoDePago`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `mydb`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PSE` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PSE` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCuenta` BIGINT(12) NOT NULL,
  PRIMARY KEY (`numeroCuenta`),
  INDEX `fk_PSE_MétodoDePago_idx` (`MétodoDePago_Cliente_IdCliente` ASC),
  CONSTRAINT `fk_PSE_MétodoDePago`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `mydb`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Daviplata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Daviplata` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Daviplata` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCelular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`numeroCelular`),
  INDEX `fk_Daviplata_MétodoDePago_idx` (`MétodoDePago_Cliente_IdCliente` ASC),
  CONSTRAINT `fk_Daviplata_MétodoDePago`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `mydb`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(60) NOT NULL,
  `precio` INT(6) NOT NULL,
  `informacionNutricional` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `tiempoPreparacion` INT(2) NOT NULL,
  `calificacion` FLOAT NOT NULL,
  `urlImagen` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Otros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Otros` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Otros` (
  `Producto_idProducto` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Otros_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Otros_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horneado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Horneado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Horneado` (
  `Producto_idProducto` INT NOT NULL,
  `contenidoGr` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Horneado_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Horneado_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empaquetado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empaquetado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empaquetado` (
  `Producto_idProducto` INT NOT NULL,
  `contenidoGr` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Empaquetado_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Empaquetado_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bebida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bebida` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bebida` (
  `Producto_idProducto` INT NOT NULL,
  `contenidoMl` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Bebida_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Bebida_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALaCarta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ALaCarta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ALaCarta` (
  `Producto_idProducto` INT NOT NULL,
  `horaInicioDisponibilidad` DATETIME NOT NULL,
  `horaFinDisponibilidad` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  INDEX `fk_ALaCarta_Producto_idx` (`Producto_idProducto` ASC),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_ALaCarta_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingrediente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingrediente` (
  `idIngrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Combo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Combo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Combo` (
  `idCombo` INT NOT NULL AUTO_INCREMENT,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idCombo`, `Producto_idProducto`),
  UNIQUE INDEX `idCombo_UNIQUE` (`idCombo` ASC),
  INDEX `fk_Combo_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Combo_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductoXCombo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductoXCombo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductoXCombo` (
  `Producto_idProducto` INT NOT NULL,
  `Combo_idCombo` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Combo_idCombo`),
  INDEX `fk_Producto_X_Combo_Combo_idx` (`Combo_idCombo` ASC),
  INDEX `fk_Producto_X_Combo_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Producto_X_Combo_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_X_Combo_Combo`
    FOREIGN KEY (`Combo_idCombo`)
    REFERENCES `mydb`.`Combo` (`idCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Basicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Basicos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Basicos` (
  `ALaCarta_Producto_idProducto` INT NOT NULL,
  `Ingrediente_idIngrediente` INT NOT NULL,
  PRIMARY KEY (`ALaCarta_Producto_idProducto`, `Ingrediente_idIngrediente`),
  INDEX `fk_ALaCarta_X_Ingrediente_Ingrediente_idx` (`Ingrediente_idIngrediente` ASC),
  INDEX `fk_Basicos_ALaCarta_idx` (`ALaCarta_Producto_idProducto` ASC),
  CONSTRAINT `fk_ALaCarta_X_Ingrediente_Ingrediente`
    FOREIGN KEY (`Ingrediente_idIngrediente`)
    REFERENCES `mydb`.`Ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Basicos_ALaCarta`
    FOREIGN KEY (`ALaCarta_Producto_idProducto`)
    REFERENCES `mydb`.`ALaCarta` (`Producto_idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PuntoDeVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PuntoDeVenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PuntoDeVenta` (
  `idPuntodeVenta` INT NOT NULL AUTO_INCREMENT,
  `Usuario_nombreUsuario` VARCHAR(20) NOT NULL,
  `Usuario_contraseña` VARCHAR(16) NOT NULL,
  `nombre` VARCHAR(18) NOT NULL,
  `tipoPuntoVenta` INT(1) NOT NULL,
  `urlUbicacion` VARCHAR(100) NOT NULL,
  `Estado` VARCHAR(12) NOT NULL,
  `urlImagen` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idPuntodeVenta`, `Usuario_nombreUsuario`, `Usuario_contraseña`),
  INDEX `fk_PuntoDeVenta_Usuario_idx` (`Usuario_nombreUsuario` ASC, `Usuario_contraseña` ASC),
  UNIQUE INDEX `idPuntodeVenta_UNIQUE` (`idPuntodeVenta` ASC),
  UNIQUE INDEX `Usuario_nombreUsuario_UNIQUE` (`Usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_PuntoDeVenta_Usuario`
    FOREIGN KEY (`Usuario_nombreUsuario` , `Usuario_contraseña`)
    REFERENCES `mydb`.`Usuario` (`nombreUsuario` , `contraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `costoTotal` INT(6) NOT NULL,
  `fechaReclamo` DATETIME NOT NULL,
  `estadoPedido` VARCHAR(10) NOT NULL,
  `razonRechazo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idPedido`, `PuntoDeVenta_idPuntodeVenta`, `Cliente_IdCliente`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_IdCliente` ASC),
  INDEX `fk_Pedido_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `mydb`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Carrito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Carrito` (
  `Producto_idProducto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `CantidadProducto` INT(2) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Pedido_idPedido`),
  INDEX `fk_Carrito_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Carrito_Pedido_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Carrito_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_Pedido`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Catalogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Catalogo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Catalogo` (
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `inventario` INT(3) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `PuntoDeVenta_idPuntodeVenta`),
  INDEX `fk_Catalogo_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  INDEX `fk_Catalogo_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Catalogo_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `mydb`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Catalogo_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Día`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Día` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Día` (
  `idDía` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idDía`),
  UNIQUE INDEX `idDía_UNIQUE` (`idDía` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Horario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `Día_idDía` INT NOT NULL,
  `horaApertura` TIME NOT NULL,
  `horaCierre` TIME NOT NULL,
  PRIMARY KEY (`idHorario`, `Día_idDía`),
  INDEX `fk_Horario_Día_idx` (`Día_idDía` ASC),
  CONSTRAINT `fk_Horario_Día`
    FOREIGN KEY (`Día_idDía`)
    REFERENCES `mydb`.`Día` (`idDía`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PuntoDeVentaXHorario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PuntoDeVentaXHorario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PuntoDeVentaXHorario` (
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  `Horario_Día_idDía` INT NOT NULL,
  PRIMARY KEY (`PuntoDeVenta_idPuntodeVenta`, `Horario_idHorario`, `Horario_Día_idDía`),
  INDEX `fk_PuntoDeVentaXHorario_Horario_idx` (`Horario_idHorario` ASC, `Horario_Día_idDía` ASC),
  INDEX `fk_PuntoDeVentaXHorario_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  CONSTRAINT `fk_PuntoDeVentaXHorario_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `mydb`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PuntoDeVentaXHorario_Horario`
    FOREIGN KEY (`Horario_idHorario` , `Horario_Día_idDía`)
    REFERENCES `mydb`.`Horario` (`idHorario` , `Día_idDía`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CierredeCaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CierredeCaja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CierredeCaja` (
  `idCierredeCaja` INT NOT NULL AUTO_INCREMENT,
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `fehaCierre` DATETIME NOT NULL,
  `totalVentasDia` BIGINT(9) NOT NULL,
  PRIMARY KEY (`idCierredeCaja`, `PuntoDeVenta_idPuntodeVenta`),
  INDEX `fk_CierredeCaja_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  UNIQUE INDEX `idCierredeCaja_UNIQUE` (`idCierredeCaja` ASC),
  CONSTRAINT `fk_CierredeCaja_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `mydb`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`ProductosMasVendidosXDia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductosMasVendidosXDia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductosMasVendidosXDia` (
  `CierredeCaja_idCierredeCaja` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Unidades` INT(4) NOT NULL,
  PRIMARY KEY (`CierredeCaja_idCierredeCaja`, `Producto_idProducto`),
  INDEX `fk_ProductosMasVendidosXDia_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_ProductosMasVendidosXDia_CierredeCaja_idx` (`CierredeCaja_idCierredeCaja` ASC),
  CONSTRAINT `fk_ProductosMasVendidosXDia_CierredeCaja`
    FOREIGN KEY (`CierredeCaja_idCierredeCaja`)
    REFERENCES `mydb`.`CierredeCaja` (`idCierredeCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosMasVendidosXDia_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductosMasIngresosXDia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProductosMasIngresosXDia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProductosMasIngresosXDia` (
  `CierredeCaja_idCierredeCaja` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `totalIngresosProducto` INT(8) NOT NULL,
  PRIMARY KEY (`CierredeCaja_idCierredeCaja`, `Producto_idProducto`),
  INDEX `fk_ProductosMasIngresosXDia_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_ProductosMasIngresosXDia_CierredeCaja_idx` (`CierredeCaja_idCierredeCaja` ASC),
  CONSTRAINT `fk_ProductosMasIngresosXDia_CierredeCaja`
    FOREIGN KEY (`CierredeCaja_idCierredeCaja`)
    REFERENCES `mydb`.`CierredeCaja` (`idCierredeCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosMasIngresosXDia_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reseña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reseña` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reseña` (
  `idReseña` INT NOT NULL AUTO_INCREMENT,
  `Cliente_IdCliente` INT NOT NULL,
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `calificacion` INT(1) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idReseña`, `Cliente_IdCliente`, `PuntoDeVenta_idPuntodeVenta`, `Producto_idProducto`),
  INDEX `fk_Reseña_Cliente_idx` (`Cliente_IdCliente` ASC),
  INDEX `fk_Reseña_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  INDEX `fk_Reseña_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Reseña_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `mydb`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseña_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `mydb`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseña_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('simon_davila', 'prueba_1');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('juan_campos', 'prueba_2');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('gabriela_camacho', 'prueba_3');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('julian_builes', 'prueba_4');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('juan_hamon', 'prueba_5');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('camilo_buitrago', 'prueba_6');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('caf_central', 'pdv_central_1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente` (`IdCliente`, `Usuario_nombreUsuario`, `Usuario_contraseña`, `nombreCompleto`, `tipoDocumento`, `idDocumento`, `correoElectronico`, `celular`) VALUES (1, 'simon_davila', 'prueba_1', 'Simón Dávila Saravia', 'CC', 1018504328, 'simondavila@javeriana.edu.co', 3108750771);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PuntoDeVenta`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PuntoDeVenta` (`idPuntodeVenta`, `Usuario_nombreUsuario`, `Usuario_contraseña`, `nombre`, `tipoPuntoVenta`, `urlUbicacion`, `Estado`, `urlImagen`) VALUES (1, 'caf_central', 'pdv_central_1', 'La Central', 1, 'https://goo.gl/maps/9o3G8fSyrHgXDo3W6', 'Abierto', 'null');

COMMIT;

