-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 20:29:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET foreign_key_checks = "ON";
-- -----------------------------------------------------
-- Schema Toppick_Schema
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Toppick_Schema` ;

-- -----------------------------------------------------
-- Schema Toppick_Schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Toppick_Schema` DEFAULT CHARACTER SET utf8 ;
USE `Toppick_Schema` ;

-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Usuario` (
  `nombreUsuario` VARCHAR(20) NOT NULL,
  `contraseña` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`nombreUsuario`, `contraseña`),
  UNIQUE INDEX `nombreUsuario_UNIQUE` (`nombreUsuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Cliente` (
  `IdCliente` INT NOT NULL AUTO_INCREMENT,
  `Usuario_nombreUsuario` VARCHAR(20) NOT NULL,
  `Usuario_contraseña` VARCHAR(16) NOT NULL,
  `nombreCompleto` VARCHAR(30) NOT NULL,
  `tipoDocumento` VARCHAR(2) NOT NULL,
  `idDocumento` BIGINT(11) NOT NULL,
  `correoElectronico` VARCHAR(40) NOT NULL COMMENT 'Create email constraint',
  `celular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`IdCliente`, `Usuario_nombreUsuario`, `Usuario_contraseña`),
  UNIQUE INDEX `IdCliente_UNIQUE` (`IdCliente` ASC),
  INDEX `fk_Cliente_Usuario_idx` (`Usuario_nombreUsuario` ASC, `Usuario_contraseña` ASC),
  UNIQUE INDEX `Usuario_nombreUsuario_UNIQUE` (`Usuario_nombreUsuario` ASC),
  UNIQUE INDEX `correoElectronico_UNIQUE` (`correoElectronico` ASC),
  UNIQUE INDEX `celular_UNIQUE` (`celular` ASC),
  CONSTRAINT `fk_Cliente_Usuario`
    FOREIGN KEY (`Usuario_nombreUsuario` , `Usuario_contraseña`)
    REFERENCES `Toppick_Schema`.`Usuario` (`nombreUsuario` , `contraseña`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`MétodoDePago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`MétodoDePago` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`MétodoDePago` (
  `Cliente_IdCliente` INT NOT NULL,
  `idMetodo` INT NOT NULL,
  PRIMARY KEY (`Cliente_IdCliente`, `idMetodo`),
  INDEX `fk_MétodoDePago_Cliente` (`Cliente_IdCliente` ASC),
  CONSTRAINT `fk_MétodoDePago_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `Toppick_Schema`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Nequi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Nequi` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Nequi` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCelular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`numeroCelular`),
  INDEX `fk_Nequi_MétodoDePago_idx` (`MétodoDePago_Cliente_IdCliente` ASC),
  CONSTRAINT `fk_Nequi_MétodoDePago`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `Toppick_Schema`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`PSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`PSE` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`PSE` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCuenta` BIGINT(12) NOT NULL,
  PRIMARY KEY (`numeroCuenta`),
  INDEX `fk_PSE_MétodoDePago_idx` (`MétodoDePago_Cliente_IdCliente` ASC),
  CONSTRAINT `fk_PSE_MétodoDePago`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `Toppick_Schema`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Daviplata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Daviplata` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Daviplata` (
  `MétodoDePago_Cliente_IdCliente` INT NOT NULL,
  `numeroCelular` BIGINT(11) NOT NULL,
  PRIMARY KEY (`numeroCelular`),
  INDEX `fk_Daviplata_MétodoDePago_idx` (`MétodoDePago_Cliente_IdCliente` ASC),
  CONSTRAINT `fk_Daviplata_MétodoDePago`
    FOREIGN KEY (`MétodoDePago_Cliente_IdCliente`)
    REFERENCES `Toppick_Schema`.`MétodoDePago` (`Cliente_IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Producto` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(60) NOT NULL,
  `precio` INT(6) NOT NULL,
  `informacionNutricional` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `tiempoPreparacion` INT(2) NOT NULL,
  `calificacion` FLOAT NOT NULL,
  `urlImagen` VARCHAR(100) NULL DEFAULT NULL,
  `categoria` VARCHAR(18) NOT NULL,
  PRIMARY KEY (`idProducto`),
  UNIQUE INDEX `idProducto_UNIQUE` (`idProducto` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Otros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Otros` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Otros` (
  `Producto_idProducto` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Otros_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Otros_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Horneado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Horneado` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Horneado` (
  `Producto_idProducto` INT NOT NULL,
  `contenidoGr` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Horneado_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Horneado_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Empaquetado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Empaquetado` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Empaquetado` (
  `Producto_idProducto` INT NOT NULL,
  `contenidoGr` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Empaquetado_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Empaquetado_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Bebida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Bebida` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Bebida` (
  `Producto_idProducto` INT NOT NULL,
  `contenidoMl` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  INDEX `fk_Bebida_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Bebida_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`ALaCarta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`ALaCarta` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`ALaCarta` (
  `Producto_idProducto` INT NOT NULL,
  `horaInicioDisponibilidad` DATETIME NOT NULL,
  `horaFinDisponibilidad` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`),
  INDEX `fk_ALaCarta_Producto_idx` (`Producto_idProducto` ASC),
  UNIQUE INDEX `Producto_idProducto_UNIQUE` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_ALaCarta_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Ingrediente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Ingrediente` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Ingrediente` (
  `idIngrediente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idIngrediente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Combo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Combo` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Combo` (
  `idCombo` INT NOT NULL AUTO_INCREMENT,
  `Producto_idProducto` INT NOT NULL,
  PRIMARY KEY (`idCombo`, `Producto_idProducto`),
  UNIQUE INDEX `idCombo_UNIQUE` (`idCombo` ASC),
  INDEX `fk_Combo_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Combo_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`ProductoXCombo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`ProductoXCombo` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`ProductoXCombo` (
  `Producto_idProducto` INT NOT NULL,
  `Combo_idCombo` INT NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Combo_idCombo`),
  INDEX `fk_Producto_X_Combo_Combo_idx` (`Combo_idCombo` ASC),
  INDEX `fk_Producto_X_Combo_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Producto_X_Combo_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_X_Combo_Combo`
    FOREIGN KEY (`Combo_idCombo`)
    REFERENCES `Toppick_Schema`.`Combo` (`idCombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Basicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Basicos` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Basicos` (
  `ALaCarta_Producto_idProducto` INT NOT NULL,
  `Ingrediente_idIngrediente` INT NOT NULL,
  `Obligatorio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`ALaCarta_Producto_idProducto`, `Ingrediente_idIngrediente`),
  INDEX `fk_ALaCarta_X_Ingrediente_Ingrediente_idx` (`Ingrediente_idIngrediente` ASC),
  INDEX `fk_Basicos_ALaCarta_idx` (`ALaCarta_Producto_idProducto` ASC),
  CONSTRAINT `fk_ALaCarta_X_Ingrediente_Ingrediente`
    FOREIGN KEY (`Ingrediente_idIngrediente`)
    REFERENCES `Toppick_Schema`.`Ingrediente` (`idIngrediente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Basicos_ALaCarta`
    FOREIGN KEY (`ALaCarta_Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`ALaCarta` (`Producto_idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`PuntoDeVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`PuntoDeVenta` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`PuntoDeVenta` (
  `idPuntodeVenta` INT NOT NULL AUTO_INCREMENT,
  `Usuario_nombreUsuario` VARCHAR(20) NOT NULL,
  `Usuario_contraseña` VARCHAR(16) NOT NULL,
  `nombre` VARCHAR(18) NOT NULL,
  `tipoPuntoVenta` INT(1) NOT NULL,
  `urlUbicacion` VARCHAR(100) NOT NULL,
  `Estado` VARCHAR(12) NOT NULL,
  `urlImagen` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idPuntodeVenta`, `Usuario_nombreUsuario`, `Usuario_contraseña`),
  INDEX `fk_PuntoDeVenta_Usuario_idx` (`Usuario_nombreUsuario` ASC, `Usuario_contraseña` ASC),
  UNIQUE INDEX `idPuntodeVenta_UNIQUE` (`idPuntodeVenta` ASC),
  UNIQUE INDEX `Usuario_nombreUsuario_UNIQUE` (`Usuario_nombreUsuario` ASC),
  CONSTRAINT `fk_PuntoDeVenta_Usuario`
    FOREIGN KEY (`Usuario_nombreUsuario` , `Usuario_contraseña`)
    REFERENCES `Toppick_Schema`.`Usuario` (`nombreUsuario` , `contraseña`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Cliente_IdCliente` INT NOT NULL,
  `fechaCreacion` DATETIME NOT NULL,
  `costoTotal` INT(6) NOT NULL,
  `fechaReclamo` DATETIME NOT NULL,
  `estadoPedido` VARCHAR(10) NOT NULL,
  `razonRechazo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idPedido`, `PuntoDeVenta_idPuntodeVenta`, `Cliente_IdCliente`),
  UNIQUE INDEX `idPedido_UNIQUE` (`idPedido` ASC),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_IdCliente` ASC),
  INDEX `fk_Pedido_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `Toppick_Schema`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `Toppick_Schema`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Carrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Carrito` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Carrito` (
  `Producto_idProducto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `CantidadProducto` INT(2) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `Pedido_idPedido`),
  INDEX `fk_Carrito_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Carrito_Pedido_idx` (`Pedido_idPedido` ASC),
  CONSTRAINT `fk_Carrito_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_Pedido`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `Toppick_Schema`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Catalogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Catalogo` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Catalogo` (
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `inventario` INT(3) NOT NULL,
  PRIMARY KEY (`Producto_idProducto`, `PuntoDeVenta_idPuntodeVenta`),
  INDEX `fk_Catalogo_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  INDEX `fk_Catalogo_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Catalogo_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `Toppick_Schema`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Catalogo_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Día`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Día` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Día` (
  `idDía` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idDía`),
  UNIQUE INDEX `idDía_UNIQUE` (`idDía` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`HoraApertura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`HoraApertura` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`HoraApertura` (
  `idHoraApertura` INT NOT NULL AUTO_INCREMENT,
  `horaApertura` TIME NOT NULL,
  PRIMARY KEY (`idHoraApertura`),
  UNIQUE INDEX `idHoraApertura_UNIQUE` (`idHoraApertura` ASC),
  UNIQUE INDEX `horaApertura_UNIQUE` (`horaApertura` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`HoraCierre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`HoraCierre` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`HoraCierre` (
  `idHoraCierre` INT NOT NULL AUTO_INCREMENT,
  `horaCierre` TIME NOT NULL,
  PRIMARY KEY (`idHoraCierre`),
  UNIQUE INDEX `idHoraApertura_UNIQUE` (`idHoraCierre` ASC),
  UNIQUE INDEX `horaApertura_UNIQUE` (`horaCierre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Horario` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `HoraApertura_idHoraApertura` INT NOT NULL,
  `HoraCierre_idHoraApertura` INT NOT NULL,
  PRIMARY KEY (`idHorario`, `HoraApertura_idHoraApertura`, `HoraCierre_idHoraApertura`),
  INDEX `fk_Horario_HoraApertura1_idx` (`HoraApertura_idHoraApertura` ASC),
  INDEX `fk_Horario_HoraCierre1_idx` (`HoraCierre_idHoraApertura` ASC),
  UNIQUE INDEX `idHorario_UNIQUE` (`idHorario` ASC),
  CONSTRAINT `fk_Horario_HoraApertura1`
    FOREIGN KEY (`HoraApertura_idHoraApertura`)
    REFERENCES `Toppick_Schema`.`HoraApertura` (`idHoraApertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Horario_HoraCierre1`
    FOREIGN KEY (`HoraCierre_idHoraApertura`)
    REFERENCES `Toppick_Schema`.`HoraCierre` (`idHoraCierre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`CierredeCaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`CierredeCaja` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`CierredeCaja` (
  `idCierredeCaja` INT NOT NULL AUTO_INCREMENT,
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `fehaCierre` DATETIME NOT NULL,
  `totalVentasDia` BIGINT(9) NOT NULL,
  PRIMARY KEY (`idCierredeCaja`, `PuntoDeVenta_idPuntodeVenta`),
  INDEX `fk_CierredeCaja_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  UNIQUE INDEX `idCierredeCaja_UNIQUE` (`idCierredeCaja` ASC),
  CONSTRAINT `fk_CierredeCaja_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `Toppick_Schema`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '		';


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`ProductosMasVendidosXDia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`ProductosMasVendidosXDia` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`ProductosMasVendidosXDia` (
  `CierredeCaja_idCierredeCaja` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `Unidades` INT(4) NOT NULL,
  PRIMARY KEY (`CierredeCaja_idCierredeCaja`, `Producto_idProducto`),
  INDEX `fk_ProductosMasVendidosXDia_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_ProductosMasVendidosXDia_CierredeCaja_idx` (`CierredeCaja_idCierredeCaja` ASC),
  CONSTRAINT `fk_ProductosMasVendidosXDia_CierredeCaja`
    FOREIGN KEY (`CierredeCaja_idCierredeCaja`)
    REFERENCES `Toppick_Schema`.`CierredeCaja` (`idCierredeCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosMasVendidosXDia_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`ProductosMasIngresosXDia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`ProductosMasIngresosXDia` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`ProductosMasIngresosXDia` (
  `CierredeCaja_idCierredeCaja` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `totalIngresosProducto` INT(8) NOT NULL,
  PRIMARY KEY (`CierredeCaja_idCierredeCaja`, `Producto_idProducto`),
  INDEX `fk_ProductosMasIngresosXDia_Producto_idx` (`Producto_idProducto` ASC),
  INDEX `fk_ProductosMasIngresosXDia_CierredeCaja_idx` (`CierredeCaja_idCierredeCaja` ASC),
  CONSTRAINT `fk_ProductosMasIngresosXDia_CierredeCaja`
    FOREIGN KEY (`CierredeCaja_idCierredeCaja`)
    REFERENCES `Toppick_Schema`.`CierredeCaja` (`idCierredeCaja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductosMasIngresosXDia_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`Reseña`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`Reseña` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`Reseña` (
  `idReseña` INT NOT NULL AUTO_INCREMENT,
  `Cliente_IdCliente` INT NOT NULL,
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `calificacion` INT(1) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idReseña`, `Cliente_IdCliente`, `PuntoDeVenta_idPuntodeVenta`, `Producto_idProducto`),
  INDEX `fk_Reseña_Cliente_idx` (`Cliente_IdCliente` ASC),
  INDEX `fk_Reseña_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  INDEX `fk_Reseña_Producto_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Reseña_Cliente`
    FOREIGN KEY (`Cliente_IdCliente`)
    REFERENCES `Toppick_Schema`.`Cliente` (`IdCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseña_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `Toppick_Schema`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reseña_Producto`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `Toppick_Schema`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Toppick_Schema`.`PuntoDeVentaXHorario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Toppick_Schema`.`PuntoDeVentaXHorario` ;

CREATE TABLE IF NOT EXISTS `Toppick_Schema`.`PuntoDeVentaXHorario` (
  `PuntoDeVenta_idPuntodeVenta` INT NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  `Día_idDía` INT NOT NULL,
  PRIMARY KEY (`PuntoDeVenta_idPuntodeVenta`, `Horario_idHorario`, `Día_idDía`),
  INDEX `fk_PuntoDeVentaXHorario_PuntoDeVenta_idx` (`PuntoDeVenta_idPuntodeVenta` ASC),
  INDEX `fk_PuntoDeVentaXHorario_Horario_idx` (`Horario_idHorario` ASC),
  INDEX `fk_PuntoDeVentaXHorario_Día1_idx` (`Día_idDía` ASC),
  CONSTRAINT `fk_PuntoDeVentaXHorario_PuntoDeVenta`
    FOREIGN KEY (`PuntoDeVenta_idPuntodeVenta`)
    REFERENCES `Toppick_Schema`.`PuntoDeVenta` (`idPuntodeVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PuntoDeVentaXHorario_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `Toppick_Schema`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PuntoDeVentaXHorario_Día1`
    FOREIGN KEY (`Día_idDía`)
    REFERENCES `Toppick_Schema`.`Día` (`idDía`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




