-- MySQL Script generated by MySQL Workbench
-- Thu Mar 18 15:32:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Data for table `mydb`.`Usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('simon_davila', 'prueba_1');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('juan_campos', 'prueba_2');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('gabriela_camacho', 'prueba_3');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('julian_builes', 'prueba_4');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('juan_hamon', 'prueba_5');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('camilo_buitrago', 'prueba_6');
INSERT INTO `mydb`.`Usuario` (`nombreUsuario`, `contraseña`) VALUES ('caf_central', 'pdv_central_1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Cliente` (`IdCliente`, `Usuario_nombreUsuario`, `Usuario_contraseña`, `nombreCompleto`, `tipoDocumento`, `idDocumento`, `correoElectronico`, `celular`) VALUES (1, 'simon_davila', 'prueba_1', 'Simón Dávila Saravia', 'CC', 1018504328, 'simondavila@javeriana.edu.co', 3108750771);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`PuntoDeVenta`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`PuntoDeVenta` (`idPuntodeVenta`, `Usuario_nombreUsuario`, `Usuario_contraseña`, `nombre`, `tipoPuntoVenta`, `urlUbicacion`, `Estado`, `urlImagen`) VALUES (1, 'caf_central', 'pdv_central_1', 'La Central', 1, 'https://goo.gl/maps/9o3G8fSyrHgXDo3W6', 'Abierto', 'null');


COMMIT;

